-- Lifeline — Tier 1 (Supabase / Postgres). Mirrors the local ledger, multi-tenant via RLS.
-- Paste it into your project's SQL Editor (Dashboard → SQL Editor → New query → Run),
-- or generate it with: `lifeline schema`.  You do NOT need to share any key to run this.
--
-- Append-only BY CONSTRUCTION: only SELECT and INSERT have a policy → UPDATE/DELETE are denied
-- by RLS. This enforces Law #2 (append-only) and Law #1 (anchor) in the database itself.

create table if not exists lifeline_entries (
  seq        bigint generated by default as identity,   -- causal order (insertion), per user/line
  owner      uuid not null default auth.uid(),           -- tenant: the entry's owner (multi-tenant)
  line       text not null default 'ledger',             -- which line (code OR conversation)
  id         text not null,                              -- content-addressed id (sha256 of content+parents)
  ts         timestamptz not null default now(),         -- metadata (outside the hash)
  kind       text not null,
  summary    text not null,
  body       text not null default '',
  parents    jsonb not null default '[]'::jsonb,
  dedup_key  text,
  payload    jsonb not null,                             -- the full Entry (Entry.model_dump_json)
  primary key (owner, line, id)                          -- dedup by content, isolated per tenant/line
);

create index if not exists idx_lifeline_owner_line_seq
  on lifeline_entries (owner, line, seq);

create unique index if not exists idx_lifeline_dedup
  on lifeline_entries (owner, line, dedup_key)
  where dedup_key is not null;

alter table lifeline_entries enable row level security;

-- Each user only READS and only INSERTS their own entries. (No UPDATE/DELETE policy
-- → RLS denies by default → append-only in the database.)
drop policy if exists "lifeline_select_own" on lifeline_entries;
create policy "lifeline_select_own" on lifeline_entries
  for select using (owner = auth.uid());

drop policy if exists "lifeline_insert_own" on lifeline_entries;
create policy "lifeline_insert_own" on lifeline_entries
  for insert with check (owner = auth.uid());


-- ============================================================================
-- HITL queue (proposals). MUTABLE — the status changes (pending→approved/rejected).
-- Unlike the ledger (append-only), RLS here ALLOWS UPDATE; but there is NO DELETE
-- policy → the curation history is preserved (you can't erase history).
-- Only what is APPROVED becomes an Entry in lifeline_entries.
-- ============================================================================
create table if not exists lifeline_proposals (
  pid       bigint generated by default as identity primary key,
  owner     uuid not null default auth.uid(),
  line      text not null default 'ledger',
  ts        timestamptz not null default now(),
  status    text not null default 'pending',
  kind      text not null,
  author    text, agent text, provider text, model text,
  summary   text not null,
  body      text not null default '',
  parents   jsonb not null default '[]'::jsonb
);

create index if not exists idx_lifeline_proposals_pending
  on lifeline_proposals (owner, line, status, pid);

alter table lifeline_proposals enable row level security;

-- The owner reads/inserts/updates their own proposals (no DELETE: curation history).
drop policy if exists "lifeline_prop_select" on lifeline_proposals;
create policy "lifeline_prop_select" on lifeline_proposals
  for select using (owner = auth.uid());

drop policy if exists "lifeline_prop_insert" on lifeline_proposals;
create policy "lifeline_prop_insert" on lifeline_proposals
  for insert with check (owner = auth.uid());

drop policy if exists "lifeline_prop_update" on lifeline_proposals;
create policy "lifeline_prop_update" on lifeline_proposals
  for update using (owner = auth.uid()) with check (owner = auth.uid());

-- (Future M4 / hub: per-line sharing policies — a per-line members table and a policy that
-- opens SELECT to members. Out of scope for Tier 1.)


-- ============================================================================
-- Authorization Server (open item #32d96c3d): persistence of DCR clients.
-- The AS (lifeline/oauth.py) runs IN MEMORY by default (correct for a single instance). For
-- multi-instance (a scaled deploy), point a client store at this table: clients registered via
-- DCR survive restarts and are shared across replicas. Codes are one-time/ephemeral (TTL ~300s)
-- and are deliberately NOT persisted here.
-- This is NOT multi-tenant by auth.uid(): client registration happens BEFORE the user logs in,
-- so the gateway uses the service key; treat it as AS infrastructure, not tenant data.
-- ============================================================================
create table if not exists lifeline_oauth_clients (
  client_id    text primary key,
  client_info  jsonb not null,                            -- OAuthClientInformationFull (DCR)
  created_at   timestamptz not null default now()
);
-- Not multi-tenant by uid (registration is pre-login), but the table MUST NOT be exposed to
-- anon/authenticated: without RLS, PostgREST would serve it via the anon key (anyone could read
-- the client_info or insert fake clients). We enable RLS with NO policy → anon/authenticated are
-- denied by default (deny-all), while `service_role` (used by the client store) BYPASSES RLS.
alter table lifeline_oauth_clients enable row level security;
