-- Lifeline — Tier 1 (Supabase / Postgres). Espelha o ledger local, multi-tenant via RLS.
-- Cole no SQL Editor do seu projeto (Dashboard → SQL Editor → New query → Run),
-- ou gere com: `lifeline schema`.  NÃO precisa compartilhar key para rodar isto.
--
-- Append-only POR CONSTRUÇÃO: só SELECT e INSERT têm policy → UPDATE/DELETE são negados
-- pela RLS. Isso impõe a Lei #2 (append-only) e a Lei #1 (âncora) no próprio banco.

create table if not exists lifeline_entries (
  seq        bigint generated by default as identity,   -- ordem causal (inserção), por usuário/line
  owner      uuid not null default auth.uid(),           -- tenant: dono da entrada (multi-tenant)
  line       text not null default 'ledger',             -- qual line (código OU conversa)
  id         text not null,                              -- id content-addressed (sha256 do conteúdo+pais)
  ts         timestamptz not null default now(),         -- metadado (fora do hash)
  kind       text not null,
  summary    text not null,
  body       text not null default '',
  parents    jsonb not null default '[]'::jsonb,
  dedup_key  text,
  payload    jsonb not null,                             -- o Entry completo (Entry.model_dump_json)
  primary key (owner, line, id)                          -- dedup por conteúdo, isolado por tenant/line
);

create index if not exists idx_lifeline_owner_line_seq
  on lifeline_entries (owner, line, seq);

create unique index if not exists idx_lifeline_dedup
  on lifeline_entries (owner, line, dedup_key)
  where dedup_key is not null;

alter table lifeline_entries enable row level security;

-- Cada usuário só LÊ e só INSERE as próprias entradas. (Sem policy de UPDATE/DELETE
-- → a RLS nega por padrão → append-only no banco.)
drop policy if exists "lifeline_select_own" on lifeline_entries;
create policy "lifeline_select_own" on lifeline_entries
  for select using (owner = auth.uid());

drop policy if exists "lifeline_insert_own" on lifeline_entries;
create policy "lifeline_insert_own" on lifeline_entries
  for insert with check (owner = auth.uid());


-- ============================================================================
-- Fila HITL (propostas). MUTÁVEL — o status muda (pending→approved/rejected).
-- Ao contrário do ledger (append-only), aqui a RLS PERMITE UPDATE; mas NÃO há
-- policy de DELETE → a curadoria fica preservada (não dá pra apagar histórico).
-- Só o que é APROVADO vira Entry em lifeline_entries.
-- ============================================================================
create table if not exists lifeline_proposals (
  pid       bigint generated by default as identity primary key,
  owner     uuid not null default auth.uid(),
  line      text not null default 'ledger',
  ts        timestamptz not null default now(),
  status    text not null default 'pending',
  kind      text not null,
  author    text, agent text, provider text, model text,
  summary   text not null,
  body      text not null default '',
  parents   jsonb not null default '[]'::jsonb
);

create index if not exists idx_lifeline_proposals_pending
  on lifeline_proposals (owner, line, status, pid);

alter table lifeline_proposals enable row level security;

-- O dono lê/insere/atualiza as próprias propostas (sem DELETE: histórico de curadoria).
drop policy if exists "lifeline_prop_select" on lifeline_proposals;
create policy "lifeline_prop_select" on lifeline_proposals
  for select using (owner = auth.uid());

drop policy if exists "lifeline_prop_insert" on lifeline_proposals;
create policy "lifeline_prop_insert" on lifeline_proposals
  for insert with check (owner = auth.uid());

drop policy if exists "lifeline_prop_update" on lifeline_proposals;
create policy "lifeline_prop_update" on lifeline_proposals
  for update using (owner = auth.uid()) with check (owner = auth.uid());

-- (Futuro M4 / hub: policies de compartilhamento por line — uma tabela de membros por line
-- e uma policy que libera SELECT a membros. Fora do escopo do Tier 1.)


-- ============================================================================
-- Authorization Server (open item #32d96c3d): persistência dos clients DCR.
-- O AS (lifeline/oauth.py) roda EM MEMÓRIA por padrão (correto p/ instância única). Para
-- multi-instância (deploy escalado), aponte um client store a esta tabela: os clients
-- registrados via DCR sobrevivem a restart e são compartilhados entre réplicas. Codes são
-- one-time/efêmeros (TTL ~300s) e NÃO se persistem aqui de propósito.
-- NÃO é multi-tenant por auth.uid(): o registro de client ocorre ANTES do login do usuário,
-- então o gateway usa a chave do serviço; trate como infraestrutura do AS, não dado de tenant.
-- ============================================================================
create table if not exists lifeline_oauth_clients (
  client_id    text primary key,
  client_info  jsonb not null,                            -- OAuthClientInformationFull (DCR)
  created_at   timestamptz not null default now()
);
-- Não é multi-tenant por uid (registro é pré-login), mas a tabela NÃO pode ficar exposta ao
-- anon/authenticated: sem RLS o PostgREST a serviria pela anon key (qualquer um leria os
-- client_info ou inseriria clients falsos). Ligamos RLS SEM nenhuma policy → anon/authenticated
-- ficam negados por padrão (deny-all), e o `service_role` (que o client store usa) IGNORA RLS.
alter table lifeline_oauth_clients enable row level security;
